# Author: Dizhong Zhu
# Date: 08/01/2025

version: '3.8'

services:
  open-webui:
    container_name: open-webui
    image: ghcr.io/open-webui/open-webui:main
    pull_policy: always
    network_mode: host
    ports:
      - "10001:8080"
    volumes:
      - open-webui:/app/backend/data
      - /home/ubuntu/SharedFile/.cred:/app/creds
#      - D:/keys:/app/creds
    environment:
      - OLLAMA_BASE_URL=http://127.0.0.1:11434
    restart: always

volumes:
  open-webui:
    name: open-webui