# Author: Dizhong Zhu
# Date: 08/01/2025

version: '3.8'
services:
  n8n:
    container_name: n8n
    image: docker.n8n.io/n8nio/n8n
    pull_policy: always
    ports:
      - "10000:5678"
    volumes:
      - n8n_data:/home/node/.n8n
    restart: always

volumes:
  n8n_data:
    name: n8n_data